POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlplUiIsImlkIjoiNjkzZmNiZTk1MWI0NTdiZTQzZjNjN2NkIiwiaWF0IjoxNzY1NzkwNzQ3fQ.GnwNO83sRhTcdQnEZkbtQlqfLJC3S9isbza0KvQr4_o

{
    "author": "Testaaja",
    "title": "Test Collection",
    "url": "www.testing.com",
    "likes": 0
}